import baselineData from "@/data/baselines.placeholder.json";
import toolsData from "@/data/tools.placeholder.json";
import pluginsData from "@/data/plugins.json";
import skillsData from "@/data/skills.json";
import type { Baseline, DetectSignals } from "@/lib/gap/types";

// ToolEntry is a provisional stand-in.

export type CatalogueEntry = {
  id: string;
  name: string;
  summary: string;
};

export type ToolEntry = CatalogueEntry & {
  category: string;
  capabilities: string[];
  stacks: string[];
  docsUrl: string;
  detect: DetectSignals;
};

export type PluginEntry = CatalogueEntry & {
  // Written here: the manifests answer "what", not "why install this".
  problem: string;
  benefits: string[];
  agents: string[];
  origin: string;
  ref: string;
  sourceRepo: string;
  homepage: string;
};

// Generated by `python -m generator` in korzainc/marketplace.
// `id` is `plugin:path`: names are not unique.
export type SkillEntry = CatalogueEntry & {
  path: string;
  plugin: string;
  origin: string;
  agents: string[];
  sourceRepo: string;
  ref: string;
  pinned: boolean;
  category: string;
  /** "setup" and "meta" are listed but never faceted. */
  kind: "skill" | "setup" | "meta";
  /** Searched, not rendered. */
  jobs: string[];
  /** Upstream's SKILL.md text: searched, not rendered. */
  description: string;
  invocation: string;
  licence: { spdx: string; osiApproved: boolean; source: string };
  /** Null when no Korza team owns it. */
  ownerTeam: string | null;
  /** Null everywhere: every derivable value restates another field. */
  maturity: string | null;
  status: string;
};

export const CATEGORIES = [
  "Discover",
  "Decide",
  "Build",
  "Document",
  "Verify",
  "Coordinate",
] as const;

/** Here, not in the component, so the tests filter with the real list. */
export const skillFacets: Facet<SkillEntry>[] = [
  { key: "category", label: "Category" },
  { key: "plugin", label: "Plugin" },
  { key: "origin", label: "Origin" },
  { key: "agents", label: "Agent" },
];

export type FacetKey<T> = {
  [K in keyof T]: T[K] extends string | string[] ? K : never;
}[keyof T] &
  string;

export type Facet<T> = {
  key: FacetKey<T>;
  label: string;
};

export function facetValues<T>(entry: T, key: FacetKey<T>): string[] {
  const value = entry[key] as string | string[];
  return Array.isArray(value) ? value : [value];
}

/** "Claude Code" -> "claude". Short enough to sit opposite the plugin on a card footer. */
export function shortAgents(agents: string[]): string[] {
  return agents.map((agent) => agent.split(" ")[0].toLowerCase());
}

export const tools: ToolEntry[] = toolsData;

export const plugins: PluginEntry[] = pluginsData;

export const skills: SkillEntry[] = (skillsData.skills as SkillEntry[]).filter(
  (skill) => skill.status !== "Planned",
);

export const browsableSkills: SkillEntry[] = skills.filter(
  (skill) => skill.kind === "skill",
);

/** Listed and searchable, but outside every facet. */
export const toolchainSkills: SkillEntry[] = skills.filter(
  (skill) => skill.kind !== "skill",
);

export const indexSchemaVersion: number = skillsData.schemaVersion;

export function skillsForPlugin(pluginId: string): SkillEntry[] {
  return skills.filter((skill) => skill.plugin === pluginId);
}

export const baseline: Baseline = baselineData;

export const marketplaceName = "korza-marketplace";

export const marketplaceRepo = "korzainc/marketplace";

export function getPlugin(id: string): PluginEntry | undefined {
  return plugins.find((plugin) => plugin.id === id);
}

export type InstallCommand = {
  agent: string;
  /** Once per machine, not once per plugin. */
  register: string;
  install: string;
};

export function installCommands(plugin: PluginEntry): InstallCommand[] {
  const all: InstallCommand[] = [
    {
      agent: "Claude Code",
      register: `/plugin marketplace add ${marketplaceRepo}`,
      install: `/plugin install ${plugin.name}@${marketplaceName}`,
    },
    {
      agent: "Codex CLI",
      register: `codex plugin marketplace add ${marketplaceRepo} --ref main`,
      install: `codex plugin add ${plugin.name}@${marketplaceName}`,
    },
  ];
  return all.filter((entry) => plugin.agents.includes(entry.agent));
}
