import type { DetectSignals } from "@/lib/gap/types";

// Client-safe: no catalogue data import, nothing here reads realCatalogueData/pluginsData/
// skillsData. `catalogue.ts` carries everything that does, guarded by `server-only` - a client
// component imports its runtime helpers and types from here instead, so bundling one can never
// pull the raw catalogue (including `detect`) into the browser along with it.

export type CatalogueEntry = {
  id: string;
  name: string;
  /** Null for a skill with no overlay entry; the card falls back to `description`. */
  summary: string | null;
};

export type ToolEntry = CatalogueEntry & {
  /** Every real tool and bundle always has one, unlike a skill's optional overlay. */
  summary: string;
  category: string;
  capabilities: string[];
  stacks: string[];
  docsUrl: string;
  problem: string;
  benefits: string[];
  /** What gap analysis looks for to decide the tool is already in use. */
  detect: DetectSignals;
};

export type BundleEntry = ToolEntry & {
  wraps: { tool: string; capabilities: string[] }[];
};

export function isBundle(entry: ToolEntry | BundleEntry): entry is BundleEntry {
  return "wraps" in entry;
}

/** What a browsing page may pass to a client component. `detect` is how gap analysis reads a
 * repo, not something a visitor to `/tools` needs shipped to their browser. */
export type PublicToolEntry = Omit<ToolEntry, "detect">;
export type PublicBundleEntry = Omit<BundleEntry, "detect">;

export function publicToolEntry<T extends ToolEntry>(
  tool: T,
): Omit<T, "detect"> {
  const { detect: _detect, ...rest } = tool;
  return rest;
}

export type PluginEntry = CatalogueEntry & {
  // Written here: the manifests answer "what", not "why install this".
  problem: string;
  benefits: string[];
  agents: string[];
  origin: string;
  ref: string;
  sourceRepo: string;
  homepage: string;
};

// Generated by `python -m generator` in korzainc/marketplace.
// `id` is `plugin:path`: names are not unique.
export type SkillEntry = CatalogueEntry & {
  path: string;
  plugin: string;
  origin: string;
  agents: string[];
  sourceRepo: string;
  ref: string;
  pinned: boolean;
  category: string;
  /** "setup" and "meta" are listed but never faceted. */
  kind: "skill" | "setup" | "meta";
  /** Searched, not rendered. */
  jobs: string[];
  /** Upstream's SKILL.md text. Searched, and rendered when `summary` is null. */
  description: string;
  invocation: string;
  licence: { spdx: string; osiApproved: boolean; source: string };
  /** Null when no Korza team owns it. */
  ownerTeam: string | null;
  /** Null everywhere: every derivable value restates another field. */
  maturity: string | null;
  status: string;
};

export const CATEGORIES = [
  "Discover",
  "Decide",
  "Build",
  "Document",
  "Verify",
  "Coordinate",
] as const;

export type FacetKey<T> = {
  [K in keyof T]: T[K] extends string | string[] ? K : never;
}[keyof T] &
  string;

export type Facet<T> = {
  key: FacetKey<T>;
  label: string;
};

export function facetValues<T>(entry: T, key: FacetKey<T>): string[] {
  const value = entry[key] as string | string[];
  return Array.isArray(value) ? value : [value];
}

/** "Claude Code" -> "claude". Short enough to sit opposite the plugin on a card footer. */
export function shortAgents(agents: string[]): string[] {
  return agents.map((agent) => agent.split(" ")[0].toLowerCase());
}

/** Here, not in the component, so the tests filter with the real list. */
export const skillFacets: Facet<SkillEntry>[] = [
  { key: "category", label: "Category" },
  { key: "plugin", label: "Plugin" },
  { key: "origin", label: "Origin" },
  { key: "agents", label: "Agent" },
];

export type InstallCommand = {
  agent: string;
  /** Once per machine, not once per plugin. */
  register: string;
  install: string;
};

/** A plugin card needs its skill count, not the skill rows themselves - computed from whatever
 * list a caller already has, so a client component never needs skills.json to show a number. */
export function skillCountByPlugin(
  skills: SkillEntry[],
): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const skill of skills) {
    counts[skill.plugin] = (counts[skill.plugin] ?? 0) + 1;
  }
  return counts;
}
