import baselineData from "@/data/baselines.placeholder.json";
import toolsData from "@/data/tools.placeholder.json";
import pluginsData from "@/data/plugins.json";
import skillsData from "@/data/skills.json";
import type { Baseline, DetectSignals } from "@/lib/gap/types";

// ToolEntry is a provisional stand-in. PluginEntry's `skills` array is no longer read.

export type CatalogueEntry = {
  id: string;
  name: string;
  summary: string;
};

export type ToolEntry = CatalogueEntry & {
  category: string;
  capabilities: string[];
  stacks: string[];
  docsUrl: string;
  detect: DetectSignals;
};

export type PluginEntry = CatalogueEntry & {
  // Written here: the manifests answer "what", not "why install this".
  problem: string;
  benefits: string[];
  agents: string[];
  origin: string;
  ref: string;
  sourceRepo: string;
  homepage: string;
  skills: string[];
};

// Generated by `python -m generator` in korzainc/marketplace.
// `id` is `plugin:path`: names are not unique.
export type SkillEntry = CatalogueEntry & {
  path: string;
  plugin: string;
  origin: string;
  agents: string[];
  sourceRepo: string;
  ref: string;
  pinned: boolean;
  category: string;
  /** "setup" and "meta" are listed but never faceted. */
  kind: "skill" | "setup" | "meta";
  /** Searched, not rendered. */
  jobs: string[];
  invocation: string;
  licence: { spdx: string; osiApproved: boolean; source: string };
  /** Null when no Korza team owns it. */
  ownerTeam: string | null;
  /** Null everywhere: every derivable value restates another field. */
  maturity: string | null;
  status: string;
};

export const CATEGORIES = [
  "Discover",
  "Decide",
  "Build",
  "Document",
  "Verify",
  "Coordinate",
] as const;

/** Here, not in the component, so the tests filter with the real list. */
export const skillFacets: Facet<SkillEntry>[] = [
  { key: "category", label: "Category" },
  { key: "plugin", label: "Plugin" },
  { key: "origin", label: "Origin" },
  { key: "agents", label: "Agent" },
];

export type FacetKey<T> = {
  [K in keyof T]: T[K] extends string | string[] ? K : never;
}[keyof T] &
  string;

export type Facet<T> = {
  key: FacetKey<T>;
  label: string;
};

export function facetValues<T>(entry: T, key: FacetKey<T>): string[] {
  const value = entry[key] as string | string[];
  return Array.isArray(value) ? value : [value];
}

export const tools: ToolEntry[] = toolsData;

export type PluginRow = PluginEntry & { pinState: string };

export const plugins: PluginEntry[] = pluginsData;

// "N behind" only means anything for an entry pinned to a tag.
export type VersionStatus = {
  state: "behind" | "current" | "unpinned" | "no-releases";
  pinned: string;
  latest: string | null;
  /** Null unless state is "behind". */
  behind: number | null;
};

// A JSON import widens every string, so `kind` arrives as `string`.
export const skills: SkillEntry[] = skillsData.skills as SkillEntry[];

export const browsableSkills: SkillEntry[] = skills.filter(
  (skill) => skill.kind === "skill",
);

/** Listed and searchable, but outside every facet. */
export const toolchainSkills: SkillEntry[] = skills.filter(
  (skill) => skill.kind !== "skill",
);

const versions = skillsData.versions as Record<string, VersionStatus>;

export function versionStatusFor(pluginId: string): VersionStatus | undefined {
  return versions[pluginId];
}

export const pluginRows: PluginRow[] = plugins.map((plugin) => ({
  ...plugin,
  pinState: versionFacetLabel(versionStatusFor(plugin.id)),
}));

/** Derived, not stored: two descriptions of one fact had drifted into a contradiction. */
export function versionFacetLabel(status: VersionStatus | undefined): string {
  switch (status?.state) {
    case "behind":
      return "Behind";
    case "current":
      return "Current";
    case "unpinned":
      return "Unpinned";
    case "no-releases":
      return "No releases";
    default:
      return "Unknown";
  }
}

/** `versions` is cast from JSON, so an unknown state reaches the default arm. */
export function describeVersion(status: VersionStatus): string {
  switch (status.state) {
    case "behind":
      return `${status.behind} version${status.behind === 1 ? "" : "s"} behind (${status.latest})`;
    case "current":
      return "current";
    case "unpinned":
      return `unpinned, upstream is at ${status.latest}`;
    case "no-releases":
      return "unpinned, upstream has no releases";
    default:
      return `pin state unknown (${String(status.state)})`;
  }
}

export const skillsArePlaceholder: boolean = skillsData.placeholder === true;

export const indexSchemaVersion: number = skillsData.schemaVersion;

export function skillsForPlugin(pluginId: string): SkillEntry[] {
  return skills.filter((skill) => skill.plugin === pluginId);
}

/** Computed, so a new overlap appears without anyone maintaining a list. */
export function claimsByName(entries: SkillEntry[]): Map<string, string[]> {
  const byName = new Map<string, Set<string>>();
  for (const skill of entries) {
    // Nobody can install a Planned skill, so it cannot compete for a name.
    if (skill.status === "Planned") continue;
    const seen = byName.get(skill.name) ?? new Set<string>();
    seen.add(skill.plugin);
    byName.set(skill.name, seen);
  }
  return new Map(
    [...byName]
      .filter(([, plugins]) => plugins.size > 1)
      .map(([name, plugins]) => [name, [...plugins].sort()]),
  );
}

export const duplicateClaims: Map<string, string[]> = claimsByName(skills);

export function rivalPlugins(skill: SkillEntry): string[] {
  return (duplicateClaims.get(skill.name) ?? []).filter(
    (plugin) => plugin !== skill.plugin,
  );
}

export const baseline: Baseline = baselineData;

export const marketplaceName = "korza-marketplace";

export const marketplaceRepo = "korzainc/marketplace";

export function getPlugin(id: string): PluginEntry | undefined {
  return plugins.find((plugin) => plugin.id === id);
}

export type InstallCommand = {
  agent: string;
  /** Once per machine, not once per plugin. */
  register: string;
  install: string;
};

export function installCommands(plugin: PluginEntry): InstallCommand[] {
  const all: InstallCommand[] = [
    {
      agent: "Claude Code",
      register: `/plugin marketplace add ${marketplaceRepo}`,
      install: `/plugin install ${plugin.name}@${marketplaceName}`,
    },
    {
      agent: "Codex CLI",
      register: `codex plugin marketplace add ${marketplaceRepo} --ref main`,
      install: `codex plugin add ${plugin.name}@${marketplaceName}`,
    },
  ];
  return all.filter((entry) => plugin.agents.includes(entry.agent));
}
