import baselineData from "@/data/baselines.placeholder.json";
import toolsData from "@/data/tools.placeholder.json";
import pluginsData from "@/data/plugins.json";
import skillsData from "@/data/skills.json";
import type { Baseline, DetectSignals } from "@/lib/gap/types";

// ToolEntry is a provisional stand-in; the real shape arrives with catalogue.json.
// PluginEntry's `skills` array is hand-typed and no longer read: counts come from the index.

export type CatalogueEntry = {
  id: string;
  name: string;
  summary: string;
};

export type ToolEntry = CatalogueEntry & {
  category: string;
  capabilities: string[];
  stacks: string[];
  docsUrl: string;
  /** What gap analysis looks for to decide the tool is already in use. */
  detect: DetectSignals;
};

export type PluginEntry = CatalogueEntry & {
  // Written here, not transcribed: the manifests answer "what" and not "why install this".
  problem: string;
  benefits: string[];
  agents: string[];
  origin: string;
  ref: string;
  sourceRepo: string;
  homepage: string;
  skills: string[];
};

// Generated by `python -m generator` in korzainc/marketplace.
// `id` is `plugin:path`: names are not unique, a plugin may ship two skills sharing one.
export type SkillEntry = CatalogueEntry & {
  path: string;
  plugin: string;
  origin: string;
  agents: string[];
  sourceRepo: string;
  ref: string;
  pinned: boolean;
  /** One value per skill, from CATEGORIES. The union of the two axes it replaced. */
  category: string;
  /** Decides whether the facets apply. "setup" and "meta" are listed but never faceted. */
  kind: "skill" | "setup" | "meta";
  /** The phrases a user would type. Searched, not rendered. */
  jobs: string[];
  /** "Agent + user", "User only" or "Planned". Derived from two front matter flags. */
  invocation: string;
  /** SPDX id read from the LICENSE file at the pinned ref, with where it was read from. */
  licence: { spdx: string; osiApproved: boolean; source: string };
  /** The Korza team that answers for this skill. Null when nobody here does. */
  ownerTeam: string | null;
  /** Support commitment. Null everywhere: every derivable value restates another field. */
  maturity: string | null;
  /** "Live" for a skill in the catalogue today, "Planned" for one we have committed to. */
  status: string;
};

/** The top-level categories, ordered as a sequence of work. */
export const CATEGORIES = [
  "Discover",
  "Decide",
  "Build",
  "Document",
  "Verify",
  "Coordinate",
] as const;

/** Here, not in the component, so the tests filter with the real list. */
export const skillFacets: Facet<SkillEntry>[] = [
  { key: "category", label: "Category" },
  { key: "plugin", label: "Plugin" },
  { key: "origin", label: "Origin" },
  { key: "agents", label: "Agent" },
];

/** Keys whose values a facet can group by: a single string, or a list of them. */
export type FacetKey<T> = {
  [K in keyof T]: T[K] extends string | string[] ? K : never;
}[keyof T] &
  string;

export type Facet<T> = {
  key: FacetKey<T>;
  label: string;
};

export function facetValues<T>(entry: T, key: FacetKey<T>): string[] {
  const value = entry[key] as string | string[];
  return Array.isArray(value) ? value : [value];
}

export const tools: ToolEntry[] = toolsData;

/** `pinState` is computed, never stored. */
export type PluginRow = PluginEntry & { pinState: string };

export const plugins: PluginEntry[] = pluginsData;

// A state machine, not a number: "N behind" only means anything for an entry pinned to a tag.
export type VersionStatus = {
  state: "behind" | "current" | "unpinned" | "no-releases";
  /** The ref the catalogue pins: a tag, or a branch name when unpinned. */
  pinned: string;
  /** Newest upstream tag, or null when upstream publishes none. */
  latest: string | null;
  /** Tags newer than the pinned one. Null unless state is "behind". */
  behind: number | null;
};

// A JSON import widens every string, so `kind` arrives as `string`. Tests check the data.
export const skills: SkillEntry[] = skillsData.skills as SkillEntry[];

/** Everything except setup and meta, which are listed but never faceted. */
export const browsableSkills: SkillEntry[] = skills.filter(
  (skill) => skill.kind === "skill",
);

/** Listed and searchable, but outside every facet. With `browsableSkills`, the whole index. */
export const toolchainSkills: SkillEntry[] = skills.filter(
  (skill) => skill.kind !== "skill",
);

const versions = skillsData.versions as Record<string, VersionStatus>;

export function versionStatusFor(pluginId: string): VersionStatus | undefined {
  return versions[pluginId];
}

export const pluginRows: PluginRow[] = plugins.map((plugin) => ({
  ...plugin,
  pinState: versionFacetLabel(versionStatusFor(plugin.id)),
}));

/** Derived, not stored: two descriptions of the same fact had drifted into a contradiction. */
export function versionFacetLabel(status: VersionStatus | undefined): string {
  switch (status?.state) {
    case "behind":
      return "Behind";
    case "current":
      return "Current";
    case "unpinned":
      return "Unpinned";
    case "no-releases":
      return "No releases";
    default:
      return "Unknown";
  }
}

/** The default arm matters: `versions` is cast from JSON, so an unknown state is reachable. */
export function describeVersion(status: VersionStatus): string {
  switch (status.state) {
    case "behind":
      return `${status.behind} version${status.behind === 1 ? "" : "s"} behind (${status.latest})`;
    case "current":
      return "current";
    case "unpinned":
      return `unpinned, upstream is at ${status.latest}`;
    case "no-releases":
      return "unpinned, upstream has no releases";
    default:
      return `pin state unknown (${String(status.state)})`;
  }
}

/** True while the skill list is the hand-extracted stand-in rather than the generated file. */
export const skillsArePlaceholder: boolean = skillsData.placeholder === true;

/** Schema version of the skill index, shown in the provenance footer. */
export const indexSchemaVersion: number = skillsData.schemaVersion;

export function skillsForPlugin(pluginId: string): SkillEntry[] {
  return skills.filter((skill) => skill.plugin === pluginId);
}

/** Computed, not curated: a new overlap appears without anyone maintaining a list. */
export function claimsByName(entries: SkillEntry[]): Map<string, string[]> {
  const byName = new Map<string, Set<string>>();
  for (const skill of entries) {
    // A Planned skill cannot compete for a name; nobody can install it.
    if (skill.status === "Planned") continue;
    const seen = byName.get(skill.name) ?? new Set<string>();
    seen.add(skill.plugin);
    byName.set(skill.name, seen);
  }
  return new Map(
    [...byName]
      .filter(([, plugins]) => plugins.size > 1)
      .map(([name, plugins]) => [name, [...plugins].sort()]),
  );
}

export const duplicateClaims: Map<string, string[]> = claimsByName(skills);

/** The other plugins claiming this skill's name, or an empty array. */
export function rivalPlugins(skill: SkillEntry): string[] {
  return (duplicateClaims.get(skill.name) ?? []).filter(
    (plugin) => plugin !== skill.plugin,
  );
}

// A statement about stacks, not about any one tool. Published separately.
export const baseline: Baseline = baselineData;

export const marketplaceName = "korza-marketplace";

export const marketplaceRepo = "korzainc/marketplace";

export function getPlugin(id: string): PluginEntry | undefined {
  return plugins.find((plugin) => plugin.id === id);
}

export type InstallCommand = {
  agent: string;
  /** Registers the marketplace. Needed once per machine, not once per plugin. */
  register: string;
  install: string;
};

/** Only the agents whose manifest actually lists the plugin get a command. */
export function installCommands(plugin: PluginEntry): InstallCommand[] {
  const all: InstallCommand[] = [
    {
      agent: "Claude Code",
      register: `/plugin marketplace add ${marketplaceRepo}`,
      install: `/plugin install ${plugin.name}@${marketplaceName}`,
    },
    {
      agent: "Codex CLI",
      register: `codex plugin marketplace add ${marketplaceRepo} --ref main`,
      install: `codex plugin add ${plugin.name}@${marketplaceName}`,
    },
  ];
  return all.filter((entry) => plugin.agents.includes(entry.agent));
}
